import {
  Banknote,
  Bell,
  BrickWall,
  Building2,
  CalendarClock,
  CheckCircle,
  Droplets,
  Fingerprint,
  Flame,
  Grid3x3,
  Hammer,
  HardHat,
  Headphones,
  Home,
  IdCard,
  IndianRupee,
  Landmark,
  Languages,
  Layers,
  LifeBuoy,
  Lock,
  MapPin,
  MapPinned,
  Paintbrush,
  Search,
  Shield,
  ShieldCheck,
  Siren,
  Star,
  StarHalf,
  Tractor,
  Truck,
  UserCheck,
  UserPlus,
  Users,
  Wallet,
  Zap,
  HelpCircle,
} from 'lucide-react'

const map = {
  shield: Shield,
  zap: Zap,
  wallet: Wallet,
  fingerprint: Fingerprint,
  layers: Layers,
  'map-pin': MapPin,
  'check-circle': CheckCircle,
  truck: Truck,
  'user-plus': UserPlus,
  'id-card': IdCard,
  bell: Bell,
  banknote: Banknote,
  'brick-wall': BrickWall,
  paintbrush: Paintbrush,
  hammer: Hammer,
  droplets: Droplets,
  flame: Flame,
  'grid-3x3': Grid3x3,
  'hard-hat': HardHat,
  tractor: Tractor,
  'map-pinned': MapPinned,
  'calendar-clock': CalendarClock,
  'indian-rupee': IndianRupee,
  siren: Siren,
  users: Users,
  languages: Languages,
  star: Star,
  'shield-check': ShieldCheck,
  headphones: Headphones,
  home: Home,
  'building-2': Building2,
  landmark: Landmark,
  'user-check': UserCheck,
  search: Search,
  'star-half': StarHalf,
  lock: Lock,
  'life-buoy': LifeBuoy,
}

export function LandingIcon({ name, className, strokeWidth = 1.75 }) {
  const Cmp = map[name] ?? HelpCircle
  return <Cmp className={className} strokeWidth={strokeWidth} aria-hidden />
}
